version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 8080 on your host machine to port 80 in the container
    volumes:
      - .:/var/www/html # Mount your local CodeIgniter directory into the container
